<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)*>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Springfield Free Press">
   <property name="name" value="All Springfield Free Press AUs" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='Springfield Free Press']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="TitlesetTestPluginHomerianResearch1">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Homerian Research" />
   <property name="issn" value="1234-4321" />
   <property name="eissn" value="4321-1234" />
   <property name="title" value="Homerian Research Volume 1" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://homer.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2010" />
   </property>
   <property name="attributes.year" value="2010" />
   <property name="attributes.volume" value="1" />
  </property>

  <property name="TitlesetTestPluginHomerianResearch2">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Homerian Research" />
   <property name="issn" value="1234-4321" />
   <property name="eissn" value="4321-1234" />
   <property name="title" value="Homerian Research Volume 2" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://homer.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2011" />
   </property>
   <property name="attributes.year" value="2011" />
   <property name="attributes.volume" value="2" />
  </property>

  <property name="TitlesetTestPluginHomerianResearch3">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Homerian Research" />
   <property name="issn" value="1234-4321" />
   <property name="eissn" value="4321-1234" />
   <property name="title" value="Homerian Research Volume 3" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://homer.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2012" />
   </property>
   <property name="attributes.year" value="2012" />
   <property name="attributes.volume" value="3" />
  </property>

  <property name="TitlesetTestPluginMargarineJournal1">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Margarine Journal" />
   <property name="issn" value="1234-1234" />
   <property name="eissn" value="4321-4321" />
   <property name="title" value="Margarine Journal Volume 1" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://marge.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2008" />
   </property>
   <property name="attributes.year" value="2008" />
   <property name="attributes.volume" value="1" />
  </property>

  <property name="TitlesetTestPluginMargarineJournal2">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Margarine Journal" />
   <property name="issn" value="1234-1234" />
   <property name="eissn" value="4321-4321" />
   <property name="title" value="Margarine Journal Volume 2" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://marge.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2009" />
   </property>
   <property name="attributes.year" value="2009" />
   <property name="attributes.volume" value="2" />
  </property>

  <property name="TitlesetTestPluginMargarineJournal3">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Margarine Journal" />
   <property name="issn" value="1234-1234" />
   <property name="eissn" value="4321-4321" />
   <property name="title" value="Margarine Journal Volume 3" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://marge.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2010" />
   </property>
   <property name="attributes.year" value="2010" />
   <property name="attributes.volume" value="3" />
  </property>

  <property name="TitlesetTestPluginMargarineJournal4">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Margarine Journal" />
   <property name="issn" value="1234-1234" />
   <property name="eissn" value="4321-4321" />
   <property name="title" value="Margarine Journal Volume 4" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://marge.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2011" />
   </property>
   <property name="attributes.year" value="2011" />
   <property name="attributes.volume" value="4" />
  </property>

  <property name="TitlesetTestPluginMargarineJournal5">
   <property name="attributes.publisher" value="Springfield Free Press" />
   <property name="journalTitle" value="Margarine Journal" />
   <property name="issn" value="1234-1234" />
   <property name="eissn" value="4321-4321" />
   <property name="title" value="Margarine Journal Volume 5" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://marge.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2012" />
   </property>
   <property name="attributes.year" value="2012" />
   <property name="attributes.volume" value="5" />
  </property>

 </property>

 <property name="org.lockss.titleSet">

  <property name="Shelbyville Jaundice Press">
   <property name="name" value="All Shelbyville Jaundice Press AUs" />
   <property name="class" value="xpath" />
   <property name="xpath" value="[attributes/publisher='Shelbyville Jaundice Press']" />
  </property>
  
 </property>
 
 <property name="org.lockss.title">

  <property name="TitlesetTestPluginBartsBoards1">
   <property name="attributes.publisher" value="Shelbyville Jaundice Press" />
   <property name="journalTitle" value="Bart's Boards" />
   <property name="issn" value="1111-1111" />
   <property name="eissn" value="1112-1112" />
   <property name="title" value="Bart's Boards Volume 1" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bart.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2010" />
   </property>
   <property name="attributes.year" value="2010" />
   <property name="attributes.volume" value="1" />
  </property>

  <property name="TitlesetTestPluginBartsBoards2">
   <property name="attributes.publisher" value="Shelbyville Jaundice Press" />
   <property name="journalTitle" value="Bart's Boards" />
   <property name="issn" value="1111-1111" />
   <property name="eissn" value="1112-1112" />
   <property name="title" value="Bart's Boards Volume 2" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bart.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2011" />
   </property>
   <property name="attributes.year" value="2011" />
   <property name="attributes.volume" value="2" />
  </property>

  <property name="TitlesetTestPluginBartsBoards3">
   <property name="attributes.publisher" value="Shelbyville Jaundice Press" />
   <property name="journalTitle" value="Bart's Boards" />
   <property name="issn" value="1111-1111" />
   <property name="eissn" value="1112-1112" />
   <property name="title" value="Bart's Boards Volume 3" />
   <property name="plugin" value="org.lockss.daemon.TitlesetTestPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bart.example.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="year" />
    <property name="value" value="2012" />
   </property>
   <property name="attributes.year" value="2012" />
   <property name="attributes.volume" value="3" />
  </property>

 </property>

</lockss-config>
